# Auto-increment build version script
# Called at build time by CMake custom command

set(VER_FILE "${SRC_DIR}/build_version.txt")
set(HDR_FILE "${SRC_DIR}/build_version.h")

# Read current version
if(EXISTS "${VER_FILE}")
    file(READ "${VER_FILE}" VER)
    string(STRIP "${VER}" VER)
    if("${VER}" STREQUAL "")
        set(VER 0)
    endif()
else()
    set(VER 0)
endif()

# Increment
math(EXPR VER "${VER} + 1")

# Write back
file(WRITE "${VER_FILE}" "${VER}\n")

# Get timestamp
string(TIMESTAMP BUILD_TS "%Y-%m-%d %H:%M:%S")

# Generate header
file(WRITE "${HDR_FILE}"
    "// Auto-generated by increment_version.cmake — do not edit\n"
    "#ifndef BUILD_VERSION_H\n"
    "#define BUILD_VERSION_H\n"
    "#define BUILD_VERSION ${VER}\n"
    "#define BUILD_TIMESTAMP \"${BUILD_TS}\"\n"
    "#endif\n"
)

message(STATUS "Build #${VER} at ${BUILD_TS}")
