import sentai
sentai.verbose(0)
sentai.tpu.load('/yolo_1_class_512_1_upsample_512_inloc_de_1024_la_P5_32.tflite')
# Initial VGA45 init then reconfigure to VGA30
sentai.camera.init(1)
sentai.rtos.sleep_ms(500)
sentai.camera.stop()
sentai.rtos.sleep_ms(500)
rc = sentai.camera.set_hw(640, 480, 30)
sentai.camera.init(1)
sentai.rtos.sleep_ms(500)
hw = sentai.camera.hw_config()
for _ in range(3): sentai.tpu.invoke()
sentai.camera.ratio(1,1)
res = ['hw=%s set_rc=%d' % (hw, rc)]
def b(pf, ipf):
    sentai.pipeline.prep_fps(pf); sentai.pipeline.invokes_per_frame(ipf)
    sentai.pipeline.prep_reset(); sentai.pipeline.infer_reset()
    sentai.pipeline.start(0.25, 0.45, 50)
    sentai.rtos.sleep_ms(3000)
    s = sentai.pipeline.infer_stats()
    sentai.pipeline.stop()
    sentai.rtos.sleep_ms(400)
    res.append('V30 pf=%d ipf=%d fps=%.1f fail=%d' % (pf,ipf,s['ok']/3,s['fail']))
for pf,ipf in [(0,1),(30,1),(30,2),(15,4)]: b(pf,ipf)
sentai.camera.ratio(0,0)
sentai.pipeline.prep_fps(0); sentai.pipeline.invokes_per_frame(1)
sentai.fs.write('/m30.txt','\n'.join(res)+'\n')
print('=== DONE ===')
